vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - RobbOwen.synthwave-vscode
    - PKief.material-icon-theme

tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      TMP_DIR="$(mktemp -d)"
      echo "Updating AWS"
      cd "${TMP_DIR}" || exit 1

      curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install --update
      rm awscliv2.zip
  - name: nodejs-dependencies
    init: |
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i
      cd $THEIA_WORKSPACE_ROOT/cognito-authz
      npm i
  - name: postgres-client
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    onOpen: ignore
    visibility: public
  - name: envoy
    port: 8800
    onOpen: ignore
    visibility: public
  - name: authz
    port: 8123
    onOpen: ignore
    visibility: public
  - name: otel-collector
    port: 4318
    onOpen: ignore
    visibility: public
