FROM node:16.18 as builder

WORKDIR /frontend-react-js

COPY package*.json .
RUN npm install

COPY public ./public
COPY src ./src
RUN npm run build

FROM nginx
LABEL org.opencontainers.image.authors="Roberto.Mora@experian.com"
LABEL org.opencontainers.image.source="https://github.com/romogo17/aws-bootcamp-cruddur-2023.git"

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /frontend-react-js/build /usr/share/nginx/html
EXPOSE 80
RUN chown nginx.nginx /usr/share/nginx/html/ -R