FROM node:16.18 as builder

WORKDIR /frontend-react-js

COPY package*.json .
RUN npm install

COPY public ./public
COPY src ./src
RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /frontend-react-js/build /usr/share/nginx/html
EXPOSE 80
RUN chown nginx.nginx /usr/share/nginx/html/ -R